---
- name: Configure iptables to allow traffic between multiple pairs of interfaces in a namespace
  hosts: localhost
  become: true
  vars_files:
    - variables/create_ip_table_rule.yaml

  tasks:
    - name: Initialize Log File
      ansible.builtin.shell: |
        echo '---------------------' > log.txt
        echo "$(date +'%Y-%m-%d %H:%M:%S') : Log started" >> log.txt
      delegate_to: localhost
      args:
        executable: /bin/bash

    - name: Allow traffic between interface pairs
      ansible.builtin.shell: |
        echo '---------------------' >> log.txt
        echo "$(date +'%Y-%m-%d %H:%M:%S') : Task: Allowing traffic from {{ item.interface1 }} to {{ item.interface2 }} in namespace {{ namespace }}" >> log.txt
        ip netns exec {{ namespace }} iptables -I FORWARD 1 -i {{ item.interface1 }} -o {{ item.interface2 }} -j ACCEPT
      loop: "{{ interface_pairs }}"
      ignore_errors: yes
      args:
        executable: /bin/bash

    - name: Allow traffic between reverse interface pairs
      ansible.builtin.shell: |
        echo '---------------------' >> log.txt
        echo "$(date +'%Y-%m-%d %H:%M:%S') : Task: Allowing reverse traffic from {{ item.interface2 }} to {{ item.interface1 }} in namespace {{ namespace }}" >> log.txt
        ip netns exec {{ namespace }} iptables -I FORWARD 1 -i {{ item.interface2 }} -o {{ item.interface1 }} -j ACCEPT
      loop: "{{ interface_pairs }}"
      ignore_errors: yes
      args:
        executable: /bin/bash

    - name: Finalize Log File
      ansible.builtin.shell: |
        echo '---------------------' >> log.txt
        echo "$(date +'%Y-%m-%d %H:%M:%S') : Log ended" >> log.txt
      delegate_to: localhost
      args:
        executable: /bin/bash
