---
- name: Configure iptables to allow traffic between multiple pairs of interfaces in a namespace
  hosts: all
  become: true
  vars_files:
    - variables/create_namespace_variables.yml

  tasks:
    - name: Allow traffic between interface pairs
      ansible.builtin.command:
        cmd: "ip netns exec {{ namespace }} iptables -A FORWARD -i {{ item.interface1 }} -o {{ item.interface2 }} -j ACCEPT"
      loop: "{{ interface_pairs }}"
      ignore_errors: yes

    - name: Allow traffic between reverse interface pairs
      ansible.builtin.command:
        cmd: "ip netns exec {{ namespace }} iptables -A FORWARD -i {{ item.interface2 }} -o {{ item.interface1 }} -j ACCEPT"
      loop: "{{ interface_pairs }}"
      ignore_errors: yes
