---
- name: Provision a new subnet in a VPC
  hosts: localhost
  gather_facts: no
  vars:
    customer_name: c1
    vpc_name: c1_vpc1
    bridge_name: c1_vpc1_br1
    network_name: c1_vpc1_nw1
    veth_ns_ep_ip: 10.10.10.1/30
    subnet_ip: 10.10.10.1
    prefix_ip: 10.10.10.0/30
    vm_name: c1_vpc1_br1_vm1
    interface_name: enp1s0
    interface_address: 10.10.10.2/30
    template_dir: "/home/vmadm/project/automation/jinja_templates"
    script_files_dir: "/home/vmadm/project/subnet_files"
    memory: 1024
    vcpu: 1

  tasks:   
    - name: Create directory for VM
      become: yes
      file:
        path: "/var/lib/libvirt/images/{{ vm_name }}"
        state: directory
        mode: '0755'

    - name: Create QCOW2 image for VM
      become: yes
      command: qemu-img create -f qcow2 -F qcow2 -o backing_file=/var/lib/libvirt/images/jammy-server-cloudimg-amd64.img "/var/lib/libvirt/images/{{ vm_name }}/{{ vm_name }}.qcow2"

    - name: Resize image
      become: yes
      command: qemu-img resize "/var/lib/libvirt/images/{{ vm_name }}/{{ vm_name }}.qcow2" 12G

    - name: Create meta data files
      ansible.builtin.template:
        src: "{{ template_dir }}/meta_data.j2"
        dest: "/var/lib/libvirt/images/{{ vm_name }}/meta-data"
      become: yes

    - name: Create user data file
      template:
        src: "{{ template_dir }}/user_data.j2"
        dest: "/var/lib/libvirt/images/{{ vm_name }}/user-data"
      become: yes    

    - name: Run genisoimage command
      command: genisoimage -output "/var/lib/libvirt/images/{{ vm_name }}/{{ vm_name }}-cidata.iso" -volid cidata -joliet -rock meta-data user-data
      args:
        chdir: "/var/lib/libvirt/images/{{ vm_name }}"
      become: yes


    - name: Generate XML files for VM definitions
      template:
        src: "{{ template_dir }}/vm_definition.j2"
        dest: "{{ script_files_dir }}/{{ vm_name }}/{{ vm_name }}.xml"


    - name: create and start a VM
      command: virsh create  "{{ script_files_dir }}/{{ vm_name }}/{{ vm_name }}.xml"
    